AWSTemplateFormatVersion: "2010-09-09"
Description:
Parameters:
  ClusterName:
    Type: String
  PreworkScriptBucket:
    Type: String
    Default: aws-quickstart
  PreworkScriptObject:
    Type: String
    Default: "quickstart-examples/blog-assets/eks-cluster-prework/scripts/pw-script.sh"
  JobName:
    Type: String
    Default: ExampleJob
  KubernetesNameSpace:
    Type: String
    Default: "prework-example"
Resources:
  KubernetesPreWorkIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "pw-role-${JobName}"   
      AssumeRolePolicyDocument: !Sub
        - |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/${OIDCProvider}"
                },
                "Action": "sts:AssumeRoleWithWebIdentity",
                "Condition": {
                  "StringEquals": {
                    "${OIDCProvider}:sub": "system:serviceaccount:${NameSpace}:${ResourceName}-${JobName}"
                  }
                }
              }
            ]
          }
        - NameSpace: !Ref KubernetesNameSpace
          ResourceName: "pw-service-account" 
      Path: "/"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  -  !Sub "arn:aws:s3:::${PreworkScriptBucket}/${PreworkScriptObject}"
  PeworkNameSpace:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref ClusterName
      Manifest: !Sub |
        kind: Namespace
        apiVersion: v1
        metadata:
          name: ${KubernetesNameSpace}
      Namespace: default
  KubernetesRole:
    Type: AWSQS::Kubernetes::Resource
    Properties:
      ClusterName: !Ref ClusterName
      Namespace: !Ref KubernetesNameSpace
      Manifest: !Sub
      - |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: Role
        metadata:
          labels:
            app.kubernetes.io/name: "${ResourceName}-${JobName}"
          name: "${ResourceName}-${JobName}"
        # Modify for your scripts here
        rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
      - ResourceName: "pw-role"
        NameSpace: !Ref "KubernetesNameSpace"

  PreWorkServiceAccount:
    Type: AWSQS::Kubernetes::Resource
    Properties:
      ClusterName: !Ref ClusterName
      Namespace: !Ref KubernetesNameSpace
      Manifest: !Sub
        - |
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            labels:
              app.kubernetes.io/name: "${ResourceName}-${JobName}"
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::${AWS::AccountId}:role/${RoleName}-${JobName}
            name: "${ResourceName}-${JobName}"
            namespace: ${NameSpace}
        - ResourceName: "pw-service-account"
          NameSpace: !Ref KubernetesNameSpace
          RoleName: !Ref "PreWorkIAMRole"

  PreWorkClusterRoleBinding:
    Type: AWSQS::Kubernetes::Resource
    Properties:
      ClusterName: !Ref ClusterName
      Namespace: !Ref KubernetesNameSpace
      Manifest: !Sub
        - |
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            labels:
              app.kubernetes.io/name: "${ResourceName}-${JobName}"
            name: "${ResourceName}-${JobName}"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: Role
            name: "pw-role-${JobName}"
          subjects:
          - kind: ServiceAccount
            name: "pw-service-account-${JobName}"
            namespace: ${NameSpace}
        - ResourceName: "pw-role-binding-${JobName}"
          NameSpace: !Ref KubernetesNameSpace

  PreWorkJob:
    DependsOn: [ PreWorkIAMRole, PreWorkRole, PreWorkServiceAccount, PreWorkRoleBinding ]
    Type: AWSQS::Kubernetes::Resource
    Properties:
      ClusterName: !Ref ClusterName
      Namespace: !Ref KubernetesNameSpace
      Manifest: !Sub
        - |
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: "${ResourceName}-${JobName}"
            namespace: ${NameSpace}
          spec:
            template:
              spec:
                containers:
                - name: ${ResourceName}
                  image: amazonlinux:2
                  command: ["/bin/bash","-c"]
                  args:
                  - >
                    sleep 15;
                    yum update -y;
                    yum install -y awscli;
                    export AWS_REGION=${AWS::Region};
                    export NS=${NameSpace};
                    aws sts get-caller-identity;
                    aws s3 cp ${!S3_SCRIPT_URL} ./prework-script.sh &&
                    chmod +x ./prework-script.sh &&
                    ./prework-script.sh
                  env:
                  - name: S3_SCRIPT_URL
                    value: ${S3ScriptURL}
                  - name: AWS_REGION
                    value: ${AWS::Region}
                serviceAccountName: "pw-service-account-${JobName}"
                restartPolicy: Never
            backoffLimit: 4
        - ResourceName: "pw-job"
          NameSpace: !Ref "KubernetesNameSpace"
          S3ScriptURL: !Sub "s3://${PreworkScriptBucket}/${PreworkScriptObject}"
